-- Seed gameQuests com 16 enigmas de farmacologia

INSERT INTO gameQuests (id, questNumber, title, npcName, npcAvatar, level, questType, description, question, options, correctAnswer, explanation, pfReward, xpReward, itemReward, week) VALUES
(1, 1, 'O Portal da Farmacocinética', 'Mestre dos Magos', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/LqVHjMPcZqkNRqHx.png', 1, 'puzzle', 'Para atravessar o portal, responda: Qual é a ordem correta dos processos farmacocinéticos?', 'Qual é a ordem correta dos processos farmacocinéticos?', '["Absorção → Distribuição → Metabolismo → Excreção (ADME)", "Distribuição → Absorção → Excreção → Metabolismo", "Metabolismo → Absorção → Distribuição → Excreção", "Excreção → Metabolismo → Distribuição → Absorção"]', 'Absorção → Distribuição → Metabolismo → Excreção (ADME)', 'ADME é a sequência correta dos processos farmacocinéticos', 50, 100, NULL, 1),

(2, 2, 'O Escudo de Sheila e a Barreira Hematoencefálica', 'Sheila', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/xBLKDYGBxULQOvFH.png', 1, 'dialogue', 'Meu escudo me protege como a barreira hematoencefálica protege o cérebro. Que característica um fármaco DEVE ter para atravessá-la?', 'Que característica um fármaco DEVE ter para atravessar a barreira hematoencefálica?', '["Alta polaridade e hidrofilicidade", "Lipofilicidade e baixo peso molecular", "Grande tamanho molecular", "Carga elétrica positiva"]', 'Lipofilicidade e baixo peso molecular', 'Fármacos lipofílicos e pequenos atravessam melhor a BHE', 75, 150, NULL, 1),

(3, 3, 'O Cajado de Presto e os Receptores', 'Presto', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/gZIBHnmCqNwUQPjH.png', 2, 'combat', 'Meu cajado se liga a alvos específicos, assim como fármacos se ligam a receptores. Qual tipo de ligação é MAIS FORTE?', 'Qual tipo de ligação fármaco-receptor é MAIS FORTE?', '["Ligação iônica", "Ligação covalente", "Ligação de hidrogênio", "Forças de Van der Waals"]', 'Ligação covalente', 'Ligações covalentes são irreversíveis e as mais fortes', 100, 200, NULL, 2),

(4, 4, 'O Arco de Hank e a Dose-Resposta', 'Hank', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/tBxIkGFGLKfGqRxE.png', 2, 'combat', 'Como um arqueiro ajusta a força do arco, médicos ajustam doses. O que é DL50?', 'O que é DL50?', '["Dose letal para 50% da população", "Dose que causa 50% do efeito máximo", "Dose mínima eficaz", "Dose de manutenção"]', 'Dose letal para 50% da população', 'DL50 é a dose letal mediana', 100, 200, NULL, 2),

(5, 5, 'O Bastão de Bobby e os Agonistas', 'Bobby', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/qPOvdYYuCYqGGUPj.png', 3, 'combat', 'Meu bastão ativa a força! Qual é a definição correta de um fármaco AGONISTA?', 'Qual é a definição correta de um fármaco AGONISTA?', '["Bloqueia receptores sem ativá-los", "Liga-se e ativa receptores produzindo resposta", "Impede ligação de outros fármacos", "Não se liga a receptores"]', 'Liga-se e ativa receptores produzindo resposta', 'Agonistas ligam e ativam receptores', 125, 250, NULL, 3),

(6, 6, 'O Clava de Eric e os Antagonistas', 'Eric', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/gEBmTwqQUOuMBjPG.png', 3, 'dialogue', 'Às vezes precisamos BLOQUEAR ameaças. Qual antagonista é usado em overdose de opioides?', 'Qual antagonista é usado em overdose de opioides?', '["Atropina", "Naloxona", "Flumazenil", "Propranolol"]', 'Naloxona', 'Naloxona é antagonista de receptores opioides', 125, 250, NULL, 3),

(7, 7, 'Uni e o Sistema Nervoso Autônomo', 'Uni', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/aGQJLbEZZOOmPRMB.png', 4, 'puzzle', 'O sistema nervoso autônomo tem duas divisões. Qual neurotransmissor é liberado pelos neurônios PARASSIMPÁTICOS pós-ganglionares?', 'Qual neurotransmissor é liberado pelos neurônios PARASSIMPÁTICOS pós-ganglionares?', '["Noradrenalina", "Dopamina", "Acetilcolina", "Serotonina"]', 'Acetilcolina', 'Neurônios parassimpáticos pós-ganglionares liberam ACh', 150, 300, NULL, 4),

(8, 8, 'A Caverna dos Receptores Colinérgicos', 'Venger', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/LqVHjMPcZqkNRqHx.png', 4, 'boss', 'Vencer Venger requer conhecimento! Qual fármaco é um antagonista MUSCARÍNICO?', 'Qual fármaco é um antagonista MUSCARÍNICO?', '["Neostigmina", "Atropina", "Succinilcolina", "Pilocarpina"]', 'Atropina', 'Atropina bloqueia receptores muscarínicos', 200, 400, 'Antídoto de Venger', 4),

(9, 9, 'O Castelo dos Adrenérgicos', 'Tiamat', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/LqVHjMPcZqkNRqHx.png', 5, 'collection', 'Cada cabeça de Tiamat representa um receptor adrenérgico. Qual receptor, quando ativado, causa BRONCODILATAÇÃO?', 'Qual receptor adrenérgico causa BRONCODILATAÇÃO quando ativado?', '["α1", "α2", "β1", "β2"]', 'β2', 'β2-agonistas relaxam músculo liso brônquico', 175, 350, NULL, 5),

(10, 10, 'A Floresta dos Anestésicos', 'Mestre dos Magos', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/LqVHjMPcZqkNRqHx.png', 5, 'dialogue', 'Na floresta do sono profundo, qual anestésico inalatório é MAIS potente?', 'Qual anestésico inalatório é MAIS potente?', '["Óxido nitroso", "Halotano", "Sevoflurano", "Desflurano"]', 'Halotano', 'Halotano tem menor CAM (concentração alveolar mínima)', 175, 350, NULL, 5),

(11, 11, 'O Labirinto dos Analgésicos', 'Hank + Sheila', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/tBxIkGFGLKfGqRxE.png', 6, 'puzzle', 'No labirinto da dor, qual analgésico NÃO é opioide?', 'Qual analgésico NÃO é opioide?', '["Morfina", "Codeína", "Paracetamol", "Tramadol"]', 'Paracetamol', 'Paracetamol é analgésico não-opioide', 200, 400, NULL, 6),

(12, 12, 'A Torre dos Anti-inflamatórios', 'Presto + Bobby', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/gZIBHnmCqNwUQPjH.png', 7, 'combat', 'Na torre da inflamação, qual enzima é inibida pelos AINEs?', 'Qual enzima é inibida pelos AINEs?', '["Lipoxigenase", "Fosfolipase A2", "Ciclooxigenase (COX)", "Tromboxano sintase"]', 'Ciclooxigenase (COX)', 'AINEs inibem COX-1 e COX-2', 225, 450, NULL, 7),

(13, 13, 'O Pântano dos Antimicrobianos', 'Eric + Uni', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/gEBmTwqQUOuMBjPG.png', 8, 'collection', 'No pântano das infecções, qual antibiótico inibe a síntese da PAREDE CELULAR bacteriana?', 'Qual antibiótico inibe a síntese da PAREDE CELULAR bacteriana?', '["Tetraciclina", "Penicilina", "Eritromicina", "Ciprofloxacino"]', 'Penicilina', 'β-lactâmicos inibem síntese de peptideoglicano', 250, 500, NULL, 8),

(14, 14, 'A Montanha dos Cardiovasculares', 'Todos os heróis', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/tBxIkGFGLKfGqRxE.png', 9, 'puzzle', 'No topo da montanha cardíaca, qual classe de fármacos inibe a ECA (enzima conversora de angiotensina)?', 'Qual classe de fármacos inibe a ECA?', '["Bloqueadores de canais de cálcio", "β-bloqueadores", "Inibidores da ECA (IECAs)", "Diuréticos tiazídicos"]', 'Inibidores da ECA (IECAs)', 'IECAs (ex: captopril, enalapril) bloqueiam conversão de Ang I → Ang II', 275, 550, NULL, 9),

(15, 15, 'O Abismo dos Psicotrópicos', 'Dungeon Master + Venger', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/LqVHjMPcZqkNRqHx.png', 9, 'boss', 'No abismo da mente, qual neurotransmissor é AUMENTADO pelos ISRSs?', 'Qual neurotransmissor é AUMENTADO pelos ISRSs (inibidores seletivos da recaptação de serotonina)?', '["Dopamina", "GABA", "Serotonina", "Glutamato"]', 'Serotonina', 'ISRSs bloqueiam recaptação de serotonina na fenda sináptica', 300, 600, 'Cristal da Clareza Mental', 9),

(16, 16, 'O Portal de Retorno - Boss Final', 'Tiamat (Forma Final)', 'https://files.manuscdn.com/user_upload_by_module/session_file/310419663028318382/LqVHjMPcZqkNRqHx.png', 10, 'boss', 'Para abrir o portal de retorno e completar Farmacologia I, responda: Qual é o principal órgão de METABOLIZAÇÃO de fármacos?', 'Qual é o principal órgão de METABOLIZAÇÃO de fármacos?', '["Rins", "Fígado", "Pulmões", "Intestino"]', 'Fígado', 'O fígado é o principal órgão de metabolização', 500, 1000, 'Título: Guardião do Conhecimento', 10);
